export const TodosActionTypes = {
  ADD_TODOS: "ADD_TODOS",
  TOGGLE_FORM: "TOGGLE_FORM",
  COMPLETE_TODO: "COMPLETE_TODO",
  UPDATING_TODO: "UPDATING_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
};
